### ISSUE TITLE
MacOS compiled with clang: error: unsupported option '-fopenmp' 

### ISSUE THREAD

**Issue by YangChaoKiKa** [dselivanov/FTRL#4]
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
* installing to library '/Library/Frameworks/R.framework/Versions/3.4/Resources/library'
* installing *source* package 'FTRL' ...
** libs
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package 'FTRL'
* removing '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/FTRL'

Exited with status 1.

I was Using mac os to compile your FTRL, It seems like R studio always use the clang coming with the apple os  installation, Can you give me some advices about to how to compile you FTRL library from command line or some another way to use you library, Thanks a lot

**Comment by dselivanov** [comment]
Issue looks little bit strange because `-fopenmp` option usually added by R automatically if openmp is available. 
R selects compiler according to your `~/.R/Makevars` file. By default(empty `Makevars` file) it uses system compiler.

My suggestions is to install `clang 4.0` (will take some time to compile):
```sh
brew install --with-clang llvm
```
And after that adjust/create `~/.R/Makevars` file and point R to use it. Something like:

```sh
# put your paths to clang-4.0 and clang++-4.0:
CC=/usr/local/opt/llvm/bin/clang
CXX=/usr/local/opt/llvm/bin/clang++
CXX11=/usr/local/opt/llvm/bin/clang++
CXX1X=/usr/local/opt/llvm/bin/clang++

#And add runtime and headers
LDFLAGS    = -L/usr/local/opt/llvm/lib
CPPFLAGS   = -I/usr/local/opt/llvm/include
```

Optionally add CPU-specific optimizations flags (below my setup for modern core i7 with `avx2`):
```
CXX11FLAGS += -O3 -ffast-math -march=native -mavx2
CXXFLAGS   += -O3 -ffast-math -march=native -mavx2
CFLAGS     += -O3 -ffast-math -march=native -mavx2
```
Let me know if this resolved your issue.

**Comment by dselivanov** [comment]
Closing.

**Comment by YangChaoKiKa** [comment]
sorry about the late respond. I will try your possible solution, it seems like the link is pretty good explanation about why this exception happened.
[https://cran.r-project.org/doc/manuals/R-exts.html#DOCF28](url)

**Comment by dselivanov** [comment]
check [here](http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/) as well
